version: '3'

services:

  app:
    image: petclinic-app
    ports:
      -  8080:8080 
    environment:
      - MYSQL_URL=jdbc:mysql://db/petclinic
      - MYSQL_PORT=3306
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic

  db:
    image: mysql:5.7
    ports:
      - 3306:3306 
    environment:
      - MYSQL_ROOT_PASSWORD= 
      - MYSQL_ALLOW_EMPTY_PASSWORD=true 
      - MYSQL_USER=petclinic 
      - MYSQL_PASSWORD=petclinic 
      - MYSQL_DATABASE=petclinic 
    volumes:
      - ./conf.d:/etc/mysql/conf.d:ro